service: SP-DeviceParam

package:
  #excludeDevDependencies: false
  exclude:
    - node_modules/**
    - '!node_modules/aws-sdk/**'
    - param/tests/**
    - param/**.ts
    - coverage/**
    - .circleci/**

plugins:
  #- serverless-localstack
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: mzilli/serverless-agent-admin
  region: us-east-1
  memorySize: 128
  timeout: 6
  custom:
    IS_OFFLINE: false # to enable offline serverless plugin
    folderName: param
    localstack: # enable localstack
      host: http://localhost
      endpointFile: path/to/file.json
    stages:
      - local
      - dev
  environment:
    DYNAMODB_TABLE: SPDeviceParam  # ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get:
    handler: ${self:provider.custom.folderName}/get.get
    name: ${self:provider.stage}-GetDeviceParamFromDynamo
    description: Get params of a Device
    events:
      - http:
          path: device/${self:provider.custom.folderName}/get
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                topic: true # required
                param: true # required

resources:
  Resources:
    SPDeviceParam:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: topic
            AttributeType: S
          -
            AttributeName: param
            AttributeType: S
        KeySchema:
          -
            AttributeName: topic
            KeyType: HASH
          -
            AttributeName: param
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}